### ISSUE TITLE
Firmware upload resets RTC

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Bootloader#16]
@davids5 A firmware update resets the RTC. Just starting the bootloader does not. It would be great if we could retain the RTC, unless there is a functionality / safety issue associated.

This is below the importance of the SD write performance though, so should come after.

**Comment by davids5** [comment]
@LorenzMeier 

This issues was caused by both the bootloader/application and nuttx using BKR0 of the RTC to store information. In the case of Nuttx it was the fact that the RTC had been started (initialised) and only need to be resumed. In the case of the bootloder/application it was used to signal a reboot that should stay in bootload mode.  

The issues has been resolved on nuttx_next, in upstream nuttx https://github.com/PX4/NuttX/commit/76cf23616b1eb151f04ffda19b375ede65639a5d by incorporating a change that allowed which back-up register, and what magic value are used by the STM32 RTC driver to determin the state as a config setting. see CONFIG_RTC_MAGIC_REG and CONFIG_RTC_MAGIC.

nuttx_next https://github.com/PX4/Firmware/commit/b0da5c7d5749f4b314b6790e929f785682dcf9ac moved nuttx to using BKR1 for it's magic.
